### ISSUE TITLE
Ошибки в конфиге для Rabbit

### ISSUE THREAD

**Issue by BatNiy** [Flexberry/NewPlatform.Flexberry.ServiceBus#65]
### Описание ошибки
В unity, в 
```xml
<register type="RabbitMQ.Client.IConnectionFactory, RabbitMQ.Client" mapTo="RabbitMQ.Client.ConnectionFactory, RabbitMQ.Client">
```
нужно добавить строку
```xml
<property name="DispatchConsumersAsync" value="true" />
```

Так чтобы получилось что-то в духе
```xml
<register mapTo="RabbitMQ.Client.ConnectionFactory, RabbitMQ.Client" type="RabbitMQ.Client.IConnectionFactory, RabbitMQ.Client">
        <lifetime type="singleton"/>
        <property name="Uri" value="amqp://%{RmqUser}%:%{RmqPassword}%@%{RmqHost}%:%{RmqAmqpPort}%/%{RmqDefaultVhost}%"/>
        <property name="Protocol">
          <dependency type="RabbitMQ.Client.Framing.Protocol, RabbitMQ.Client"/>
        </property>
        <property name="DispatchConsumersAsync" value="true" />
</register>
```

В противном случае доставка сообщений по callback не будет работать.

### Пути решения
Нужно править [конфиг.](https://github.com/Flexberry/NewPlatform.Flexberry.ServiceBus/blob/develop/NewPlatform.Flexberry.ServiceBus.WinServiceHost/App.RMQ.config)

**Comment by TeterinaSvetlana** [comment]
#66

**Comment by BatNiy** [comment]
https://github.com/Flexberry/NewPlatform.Flexberry.ServiceBus/blob/c84b028421d4835dfa81a4144669edc4a951e39c/NewPlatform.Flexberry.ServiceBus.WinServiceHost/App.RMQ.config#L209

Здесь нужно упустить имя и логин пользователя. Т.к. 
1. В коде тоже значения проставляются https://github.com/Flexberry/NewPlatform.Flexberry.ServiceBus/blob/70cc66c56e710603f78e0770a47f497cebbdff8b/NewPlatform.Flexberry.ServiceBus.RabbitMQ/Components/ReceivingManager/RmqReceivingManager.cs#L30
2. Это приводит к неправильному логину/паролю при приёме сообщений, т.к. данные перезаписываются из Uri
